import type { Metadata } from "next";
import "./globals.css";
import "./StaggeredMenu.css";
import { tomorrow } from "@/app/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
        />
      </head>
      <body
        className={`${tomorrow.className} antialiased bg-bg-offwhite text-brand-dark overflow-x-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
