import type { Metadata } from "next";
import "./globals.css";
import "./StaggeredMenu.css";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { montserrat, tomorrow } from "@/app/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
        />
      </head>
      <body
        className={`${tomorrow.className} antialiased bg-bg-offwhite text-brand-dark overflow-x-hidden`}
      >
        <div className="min-h-screen bg-bg-offwhite bg-[url('/Background%20website.png')] bg-cover bg-center overflow-x-hidden">
          <Header />
          <div className="pt-20">
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
